
type IconsType = 
    | `user` 
    | `dashboard` 
    | `payments` 
    | `config` 
    | `subscription` 
    | `logout` 
    | `singin` 
    | `create` 
    | `update` 
    | `reload` 
    | `delete` 
    | `delete-row` 
    | `report` 
    | `list`
    | `unique`
    | `shop`
    | `select`
    | `drop`
    | `down`
    | `change`
    | `reload`
    | `money`
    | `master`
    | `secure`
    | `return`
    | `image`
    | `success`
    | `info`
    | `error`
    | `x`
    | `notification`
    | `warning`
    | `finanzas`
    | `distribucion`
    | `menu`    
    | `exchange`    
    | `agend`    
    | `consult` 
    ;

type ObjectSupport = 
    | `user`
    | `payment`
    | `user/payment`
    | `user/wallet`
    | `user/payment/register`
    | `user/transaction`
    | `subscription`
    | `user/subscription`
    | `user/subscription/ficha`
    | `subscription/detail`
    | `dashboard`
    | `group`
    | ``
    | `finanzas`
    | `nutrition`    
    | `presentation`    
    | `food`    
    | `efood`  
    | `master`
    | `pharmacy`
    | `pharmacy/presentation`
    | `supplement`
    | `supplement/presentation`
    | ``
    | `menu`
    | `menu/detail`
    | `consult/menu`
    | `consult/menu/string`
    | `exchange`
    | `consult/exchange`
    | `consult/exchange/string`
    | `agend`
    | `consult/agend`
    | `consult`
    | string

export { IconsType, ObjectSupport }
